import type {
  RuntimeTemplateDocument,
  RuntimeTemplateEditorState,
} from "@/lib/runtime-templates/schema.zod";

export function createStarterRuntimeTemplateDocument(input?: {
  name?: string;
  description?: string;
}): RuntimeTemplateDocument {
  const name = input?.name?.trim() || "Starter Custom Template";
  const description =
    input?.description?.trim() ||
    "Starter runtime template draft for the Phase 1 custom-template foundation.";

  return {
    schemaVersion: 1,
    templateKind: "custom-runtime",
    canvas: {
      width: 1080,
      height: 1920,
      safeInset: 36,
    },
    metadata: {
      name,
      description,
      category: "custom",
      tags: ["starter", "runtime"],
    },
    capabilities: {
      supportsSubtitle: true,
      supportsItemNumber: true,
      supportsDomain: true,
      imageSlotCount: 1,
    },
    presetPolicy: {
      allowVisualPresetOverride: true,
      allowedPresetIds: [],
      allowedPresetCategories: [
        "editorial-soft",
        "pastel-soft",
        "earthy-warm",
        "dark-drama",
        "graphic-pop",
        "fresh-vivid",
        "feminine-bold",
      ],
      tokenMode: "preset-bound",
    },
    background: {
      fillToken: "surface.canvas",
    },
    presetOverrides: {},
    elements: [
      {
        id: "image-hero",
        type: "imageFrame",
        name: "Hero image",
        x: 36,
        y: 36,
        width: 1008,
        height: 1084,
        rotation: 0,
        zIndex: 10,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "backgroundImage",
        slotIndex: 0,
        shapeKind: "roundedRect",
        fitMode: "cover",
        styleTokens: {
          fillToken: "surface.secondary",
          borderToken: "border.primary",
          shadowToken: "shadow.none",
          borderRadius: 28,
          overlayGradient: "none",
          overlayOpacity: 0.18,
        },
      },
      {
        id: "shape-title-card",
        type: "shapeBlock",
        name: "Editorial card",
        x: 56,
        y: 1158,
        width: 968,
        height: 564,
        rotation: 0,
        zIndex: 20,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "decorative",
        shapeKind: "roundedRect",
        styleTokens: {
          fillToken: "surface.primary",
          borderToken: "border.primary",
          shadowToken: "shadow.soft",
          borderRadius: 30,
        },
      },
      {
        id: "subtitle-main",
        type: "subtitleText",
        name: "Kicker",
        x: 148,
        y: 1218,
        width: 784,
        height: 54,
        rotation: 0,
        zIndex: 30,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "subtitle",
        hideWhenEmpty: true,
        text: "",
        styleTokens: {
          textToken: "text.title",
          fontToken: "font.subtitle",
          textAlign: "center",
          textTransform: "uppercase",
          minFontSize: 22,
          maxFontSize: 34,
          maxLines: 1,
          lineHeight: 1.04,
          letterSpacing: 0.12,
          autoFit: true,
        },
      },
      {
        id: "number-main",
        type: "numberText",
        name: "Hero number",
        x: 120,
        y: 1288,
        width: 180,
        height: 140,
        rotation: 0,
        zIndex: 30,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "itemNumber",
        hideWhenEmpty: true,
        text: "",
        styleTokens: {
          textToken: "text.number",
          fontToken: "font.number",
          textAlign: "left",
          textTransform: "none",
          minFontSize: 88,
          maxFontSize: 126,
          maxLines: 1,
          lineHeight: 0.88,
          letterSpacing: -0.06,
          autoFit: true,
        },
      },
      {
        id: "title-main",
        type: "titleText",
        name: "Main title",
        x: 148,
        y: 1318,
        width: 784,
        height: 228,
        rotation: 0,
        zIndex: 30,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "title",
        text: "",
        hideWhenEmpty: false,
        styleTokens: {
          textToken: "text.title",
          fontToken: "font.title",
          textAlign: "center",
          textTransform: "none",
          minFontSize: 46,
          maxFontSize: 92,
          maxLines: 3,
          lineHeight: 1.08,
          letterSpacing: -0.02,
          autoFit: true,
        },
      },
      {
        id: "divider-domain",
        type: "divider",
        name: "Domain divider",
        x: 396,
        y: 1580,
        width: 300,
        height: 2,
        rotation: 0,
        zIndex: 30,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "decorative",
        styleTokens: {
          borderToken: "border.accent",
        },
        strokeWidth: 2,
      },
      {
        id: "domain-main",
        type: "domainText",
        name: "Domain label",
        x: 222,
        y: 1622,
        width: 560,
        height: 50,
        rotation: 0,
        zIndex: 30,
        visible: true,
        locked: false,
        opacity: 1,
        semanticRole: "domain",
        sanitizeDomain: true,
        hideWhenEmpty: false,
        text: "",
        styleTokens: {
          textToken: "text.title",
          fontToken: "font.meta",
          textAlign: "center",
          textTransform: "none",
          minFontSize: 24,
          maxFontSize: 32,
          maxLines: 1,
          lineHeight: 1,
          letterSpacing: 0,
          autoFit: true,
        },
      },
    ],
    validationRules: {
      imagePolicy: {
        minSlotsRequired: 1,
        mode: "ALLOW_FEWER_DUPLICATE_LAST",
      },
      ignoredIssues: [],
    },
  };
}

export function createDefaultRuntimeTemplateEditorState(): RuntimeTemplateEditorState {
  return {
    selectedElementId: null,
    zoom: 0.42,
    visualPreset: null,
    previewContent: {
      title: "24 Cozy Reading Room Ideas To Copy",
      subtitle: "Warm Layers And Better Lighting",
      itemNumber: 24,
      domain: "mightypaint.com",
      ctaText: "Read more",
    },
    showSafeArea: true,
    showGuides: true,
    collapsedPanels: [],
  };
}
