import {
  templateBlockContentSchema,
  type TemplateBlockContent,
} from "@/lib/template-blocks/schema";

export type StarterTemplateBlock = {
  id: string;
  name: string;
  description: string;
  category: "starter";
  content: TemplateBlockContent;
};

export const starterTemplateBlocks: StarterTemplateBlock[] = [
  {
    id: "starter-hero-card-stack",
    name: "Hero card stack",
    description: "Rounded card with kicker and centered title stack.",
    category: "starter",
    content: templateBlockContentSchema.parse({
      schemaVersion: 1,
      bounds: {
        width: 760,
        height: 360,
      },
      elements: [
        {
          id: "shape-hero-card",
          type: "shapeBlock",
          name: "Hero card",
          x: 0,
          y: 0,
          width: 760,
          height: 360,
          rotation: 0,
          zIndex: 10,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "decorative",
          shapeKind: "roundedRect",
          styleTokens: {
            fillToken: "surface.primary",
            borderToken: "border.primary",
            shadowToken: "shadow.soft",
            borderRadius: 28,
          },
        },
        {
          id: "label-kicker",
          type: "subtitleText",
          name: "Kicker",
          x: 88,
          y: 42,
          width: 584,
          height: 48,
          rotation: 0,
          zIndex: 20,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "subtitle",
          text: "",
          hideWhenEmpty: true,
          styleTokens: {
            textToken: "text.subtitle",
            fontToken: "font.subtitle",
            textAlign: "center",
            textTransform: "uppercase",
            minFontSize: 20,
            maxFontSize: 32,
            maxLines: 1,
            lineHeight: 1.02,
            letterSpacing: 0.16,
            autoFit: true,
          },
        },
        {
          id: "title-main",
          type: "titleText",
          name: "Main title",
          x: 84,
          y: 108,
          width: 592,
          height: 184,
          rotation: 0,
          zIndex: 20,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "title",
          text: "",
          hideWhenEmpty: false,
          styleTokens: {
            textToken: "text.title",
            fontToken: "font.title",
            textAlign: "center",
            textTransform: "none",
            minFontSize: 42,
            maxFontSize: 82,
            maxLines: 3,
            lineHeight: 1.04,
            letterSpacing: -0.03,
            autoFit: true,
          },
        },
      ],
    }),
  },
  {
    id: "starter-number-badge",
    name: "Number badge",
    description: "Circular hero count badge with centered number.",
    category: "starter",
    content: templateBlockContentSchema.parse({
      schemaVersion: 1,
      bounds: {
        width: 220,
        height: 220,
      },
      elements: [
        {
          id: "shape-badge",
          type: "shapeBlock",
          name: "Badge",
          x: 0,
          y: 0,
          width: 220,
          height: 220,
          rotation: 0,
          zIndex: 10,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "decorative",
          shapeKind: "circle",
          styleTokens: {
            fillToken: "surface.secondary",
            borderToken: "border.primary",
            shadowToken: "shadow.soft",
            borderRadius: 999,
          },
        },
        {
          id: "number-main",
          type: "numberText",
          name: "Hero number",
          x: 28,
          y: 34,
          width: 164,
          height: 152,
          rotation: 0,
          zIndex: 20,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "itemNumber",
          text: "",
          hideWhenEmpty: true,
          styleTokens: {
            textToken: "text.number",
            fontToken: "font.number",
            textAlign: "center",
            textTransform: "none",
            minFontSize: 80,
            maxFontSize: 124,
            maxLines: 1,
            lineHeight: 0.9,
            letterSpacing: -0.05,
            autoFit: true,
          },
        },
      ],
    }),
  },
  {
    id: "starter-domain-pill",
    name: "Domain pill",
    description: "Rounded footer pill for domain or source label.",
    category: "starter",
    content: templateBlockContentSchema.parse({
      schemaVersion: 1,
      bounds: {
        width: 420,
        height: 72,
      },
      elements: [
        {
          id: "shape-pill",
          type: "shapeBlock",
          name: "Domain pill",
          x: 0,
          y: 0,
          width: 420,
          height: 72,
          rotation: 0,
          zIndex: 10,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "decorative",
          shapeKind: "pill",
          styleTokens: {
            fillToken: "surface.badge",
            borderToken: "border.primary",
            shadowToken: "shadow.soft",
            borderRadius: 999,
          },
        },
        {
          id: "domain-main",
          type: "domainText",
          name: "Domain",
          x: 36,
          y: 12,
          width: 348,
          height: 42,
          rotation: 0,
          zIndex: 20,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "domain",
          sanitizeDomain: true,
          text: "",
          hideWhenEmpty: false,
          styleTokens: {
            textToken: "text.cta",
            fontToken: "font.meta",
            textAlign: "center",
            textTransform: "uppercase",
            minFontSize: 18,
            maxFontSize: 28,
            maxLines: 1,
            lineHeight: 1,
            letterSpacing: 0.08,
            autoFit: true,
          },
        },
      ],
    }),
  },
  {
    id: "starter-image-pair",
    name: "Image pair",
    description: "Two rounded image frames for a simple split section.",
    category: "starter",
    content: templateBlockContentSchema.parse({
      schemaVersion: 1,
      bounds: {
        width: 760,
        height: 420,
      },
      elements: [
        {
          id: "image-left",
          type: "imageFrame",
          name: "Image left",
          x: 0,
          y: 0,
          width: 366,
          height: 420,
          rotation: 0,
          zIndex: 10,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "imageSlot",
          slotIndex: 0,
          shapeKind: "roundedRect",
          fitMode: "cover",
          focalPoint: {
            x: 0.5,
            y: 0.5,
          },
          styleTokens: {
            fillToken: "surface.secondary",
            borderToken: "border.primary",
            shadowToken: "shadow.none",
            borderRadius: 22,
            overlayGradient: "none",
            overlayOpacity: 0,
          },
        },
        {
          id: "image-right",
          type: "imageFrame",
          name: "Image right",
          x: 394,
          y: 0,
          width: 366,
          height: 420,
          rotation: 0,
          zIndex: 20,
          visible: true,
          locked: false,
          opacity: 1,
          semanticRole: "imageSlot",
          slotIndex: 1,
          shapeKind: "roundedRect",
          fitMode: "cover",
          focalPoint: {
            x: 0.5,
            y: 0.5,
          },
          styleTokens: {
            fillToken: "surface.secondary",
            borderToken: "border.primary",
            shadowToken: "shadow.none",
            borderRadius: 22,
            overlayGradient: "none",
            overlayOpacity: 0,
          },
        },
      ],
    }),
  },
];
